<a href="https://colab.research.google.com/github/GladiusRegis/data_science/blob/main/array_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])

In [5]:
A + B

array([6, 0, 7, 4])

In [6]:
A - B

array([0, 2, 1, 0])

In [10]:
A * B

array([ 9, -1, 12,  4])

In [11]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [12]:
A + 3

array([6, 4, 7, 5])

In [14]:
abs(B)

array([3, 1, 3, 2])

In [ ]:
abs(A)

In [16]:
A + 3*B

array([12, -2, 13,  8])

In [17]:
np.add(A, B)

array([6, 0, 7, 4])

In [18]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [19]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [20]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [22]:
x = np.array([[1, 3], [-2, 0]])
y = np.array([[6, 0], [-1,2]])
np.dot(x, y)

array([[  3,   6],
       [-12,   0]])

In [23]:
x.dot(y)

array([[  3,   6],
       [-12,   0]])

In [24]:
x @ y

array([[  3,   6],
       [-12,   0]])