<a href="https://colab.research.google.com/github/GladiusRegis/data_science/blob/main/data_types.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 
np.__version__

'1.21.6'

In [ ]:
dir(np)

In [ ]:
help(np.array)

1D Array

In [4]:
x = np.array([1, 3,])
x

array([1, 3])

In [5]:
print(x)

[1 3]


In [6]:
type(x)

numpy.ndarray

In [7]:
x.ndim

1

In [8]:
x.shape

(2,)

In [9]:
x.size

2

In [10]:
x.dtype

dtype('int64')

In [12]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [16]:
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)

1
(3,)
3
float64


In [18]:
x = np.array([[1, 2], [-3, 1]])
print (x)

[[ 1  2]
 [-3  1]]


In [19]:
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)

2
(2, 2)
4
int64


2D Array

In [20]:
x = np.array([[2, 3, 5], [5, 3, 5]])
print(x)

[[2 3 5]
 [5 3 5]]


In [21]:
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)

2
(2, 3)
6
int64


3D Array

In [23]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
     [[4, 1, 3],
      [4, 2, 1]]]
)

In [24]:
print(x)

[[[4 3 1]
  [3 1 2]]

 [[4 1 3]
  [4 2 1]]]


In [26]:
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)

3
(2, 2, 3)
12
int64


#Typy danych

In [29]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [34]:
A = np.array([1, 2, 3], dtype='complex')
print(A.dtype)
print(A)

complex128
[1.+0.j 2.+0.j 3.+0.j]


In [35]:
A = np.array([24, 120, 230], dtype=np.int8)

In [37]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')